spring.application.name=proctor

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/exam_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Properties (Creates / Updates tables automatically)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Redis Configuration for Violations Points Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
